---
  - include_tasks: ubuntu.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install strongSwan
    package: name=strongswan state=present

  - name: IPsec Configuation
    include_tasks: ipsec_configuration.yml
    include_tasks: distribute_keys.yml
    include_taks:  client_configs.yml
    delegate_to: localhost
    become: false
    tags: update-users

  - name: strongSwan started
    service:
      name: strongswan
      state: started
      enabled: true

  - meta: flush_handlers
rescue:
  - debug: var=fail_hint
    tags: always
  - fail:
    tags: always
